"use client"; // top to the file
import { Inter } from "next/font/google";
import "./globals.css";
import { Auth0Provider } from "@auth0/auth0-react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Auth0Provider
        domain="dev-y1rod1koewo1mwon.us.auth0.com"
        clientId="FCLYEXmwR655OOHni4fUfMObPIHNGzEG"
        authorizationParams={{
          redirect_uri: "http://localhost:3000",
        }}
      >
        <body className={inter.className}>{children}</body>
      </Auth0Provider>
    </html>
  );
}
